# List of objects for the project's library
phjlib.a_OBJS = $(MODULES)/helpers/helpers.o \
                $(MODULES)/hopscotch/hash.o \
                $(MODULES)/hopscotch/hopscotch.o \
                $(MODULES)/phjoin/jobs.o \
                $(MODULES)/phjoin/phjoin.o \
                $(MODULES)/query/query.o \
                $(MODULES)/relation/relation.o \
                $(MODULES)/optimizer/optimizer.o \
                $(MODULES)/scheduler/scheduler.o


include ../common.mk
